### ISSUE TITLE
send /new /voice command response EdgeGPT API not available. Try again later.

### ISSUE THREAD

**Issue by hdcola** [scmanjarrez/Edge-GPT-Telegram-Bot#19]
### The problem

<img width="662" alt="image" src="https://user-images.githubusercontent.com/1254855/225804539-fcc52224-b8bb-47a6-8acc-45307972134d.png">
2023-03-16 23:19:23,854 - EdgeGPT - ERROR - Authentication failed. You have not been accepted into the beta.

### Version of Edge-GPT-Telegram-Bot

edge-gpt-telegram-bot v0.1.0

### Operating system running Edge-GPT-Telegram-Bot

MacOS Linux

### Running on your machine? Running on docker?

machine and docker

**Comment by hdcola** [comment]
This is my problem.
/voice move to /setting
cookies need update

**Comment by scmanjarrez** [comment]
Yes, I need to regenerate the cookies file every few days
