### ISSUE TITLE
Error when trying to run

### ISSUE THREAD

**Issue by tmatzxzone** [scmanjarrez/Edge-GPT-Telegram-Bot#8]
`2023-03-06 22:23:15,442 - root - ERROR - .config.json or .cookies.json file missing.`

Running on ubuntu with Python 3.7.3
.config.json file already have but not .cookies.json

**Comment by scmanjarrez** [comment]
Can you set your .config.json webhook to false and check again? Most likely telegram server is not able to contact with your server.

**Comment by tmatzxzone** [comment]
> 

yea that's what i did and it work fine
